#ifndef CONSTANTESYMACROS_H_INCLUDED
#define CONSTANTESYMACROS_H_INCLUDED

#define ADELANTE 1
#define ATRAS -1
#define TODO_OK 1
#define LISTA_ERROR -1
#define SIN_MEM -2
#define DUPLICADO_ERROR -3
#define COLA_ERROR -4
#define ARCH_ERROR -5
#define LIMITE_INVALIDO -6

#define MIN(x,y)(x>y?y:x)

#endif // CONSTANTESYMACROS_H_INCLUDED
